# Generated by Django 6.0.2 on 2026-05-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
